# Generated by Django 5.0.6 on 2024-07-04 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=12, unique=True
                    ),
                ),
                (
                    "side",
                    models.SmallIntegerField(choices=[(1, "Buyer"), (2, "Seller")]),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "rating_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
                (
                    "target_verifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.verifier",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matching.transaction",
                    ),
                ),
            ],
        ),
    ]
